### ISSUE TITLE
issue with node setup

### ISSUE THREAD

**Issue by CyberBishop** [kentcdodds/react-fundamentals#284] opened 2022-07-19 19:48 UTC
when I run this:
```
git clone https://github.com/kentcdodds/react-fundamentals.git
cd react-fundamentals
node setup
```

I get this error:
```
node setup
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/workshop-computer-validator - Not found
npm ERR! 404 
npm ERR! 404  'workshop-computer-validator@1.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alvin/.npm/_logs/2022-07-19T19_25_40_307Z-debug-0.log
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

**Comment by kentcdodds** [comment] 2022-07-19 21:53
Hi @CyberBishop,

You're going to have to go with the workarounds in the README for now. This is a duplicate of issue #279

**Closed by kentcdodds** 2022-07-19 21:53 UTC
