### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ismaelmkumbi** [kentcdodds/react-fundamentals#280] opened 2022-07-04 19:27 UTC
message from terminal:    ```
   Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
'workshop-setup' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by reeceosborn-toast** [comment] 2022-07-05 14:02
I run into the same exact issue

**Comment by smasinde** [comment] 2022-07-07 09:14
I'm getting something similar:
`  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
sh: workshop-setup: command not found`

**Comment by kentcdodds** [comment] 2022-07-07 18:51
Duplicate of #279

**Closed by kentcdodds** 2022-07-07 18:51 UTC
